cursopython2023-main/aula207_ola_django/blog/urls.py
from blog import views
from django.urls import path

app_name = 'blog'

# blog/
# Django URLs:
# https://docs.djangoproject.com/en/4.2/topics/http/urls/
urlpatterns = [
    path('', views.blog, name='home'),
    path('<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo'),
]

cursopython2023-main/aula207_ola_django/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

cursopython2023-main/aula207_ola_django/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

cursopython2023-main/aula207_ola_django/blog/models.py
from django.db import models

# Create your models here.

cursopython2023-main/aula207_ola_django/home/models.py
from django.db import models

# Create your models here.

cursopython2023-main/aula207_ola_django/blog/views.py
from typing import Any

from blog.data import posts
from django.http import Http404, HttpRequest
from django.shortcuts import render


def blog(request):
    print('blog')

    context = {
        # 'text': 'Olá blog',
        'posts': posts
    }

    return render(
        request,
        'blog/index.html',
        context
    )


def post(request: HttpRequest, post_id: int):
    found_post: dict[str, Any] | None = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Http404('Post não existe.')

    context = {
        # 'text': 'Olá blog',
        'post': found_post,
        'title': found_post['title'] + ' - ',
    }

    return render(
        request,
        'blog/post.html',
        context
    )


def exemplo(request):
    print('exemplo')

    context = {
        'text': 'Olá exemplo',
        'title': 'Essa é uma página de exemplo - ',
    }

    return render(
        request,
        'blog/exemplo.html',
        context
    )

cursopython2023-main/aula207_ola_django/home/views.py
from django.shortcuts import render


def home(request):
    print('home')

    context = {
        'text': 'Olá home'
    }

    return render(
        request,
        'home/index.html',
        context,
    )

cursopython2023-main/aula207_ola_django/blog/templates/blog/exemplo.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

cursopython2023-main/aula207_ola_django/blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
  {% for post in posts %}
    {% include 'global/partials/postblock.html' %}
  {% endfor %}
{% endblock posts %}

cursopython2023-main/aula207_ola_django/blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
  <article class="post single-post">
    <header>
      <h1 class="post__title">
        <a href="{% url 'blog:post' post.id %}">
          {{ post.title }}
        </a>
      </h1>
    </header>
    <div class="post__body">{{ post.body }}</div>
  </article>
{% endblock posts %}

cursopython2023-main/aula207_ola_django/home/templates/home/index.html
{% extends 'global/base.html' %}

{% block texto %} 
  {{ text }}
{% endblock texto %}

{% block home %}
  <h1>HOME</h1>
{% endblock home %}